### ISSUE TITLE
Add support to Aranet4 HOME sensor

### ISSUE THREAD

**Issue by atallo** [custom-components/sensor.airthings_wave#83]
I currently have this device:

Product info: https://aranet.com/product/aranet4-sensor/
Product datasheet: https://cdn.bfldr.com/FS48XT6B/at/k9b9wjnv8f455crkp7846j/Aranet4_datasheet_WEB.pdf
Python commandline implementation: https://github.com/Anrijs/Aranet4-Python

It is quite a popular product, but it does not have native integration with Home Assistant.

From what I see functionally it is almost the same as the device of AirThings. Both functionally and in the way of obtaining the data.

I have no experience programming with python, But, I think it would be easy to adapt this component to use it with other devices like Aranet.

Please, I would be very grateful if you consider this request.

Thank you

**Comment by MartyTremblay** [comment]
Thanks for the info. I does indeed allow communication of BLE and the message protocol is similar with how Airwaves does it. However, there is still substantial differences between the 2 payloads which would make it impractical to combine the two devices in a single component.  

I wish I could help you with this but I don't have a Aranet4 device to develop with, and more importantly, I have little time to dedicate for such a project.

I'll reopen the issue so that someone from the community may pick it up.

**Comment by atallo** [comment]
Currently the integration already exists. Thanks for the help.

https://www.home-assistant.io/integrations/aranet/
